name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  YARN_ENABLE_GLOBAL_CACHE: false

jobs:
  commit-lint:
    name: Commit Lint
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6

  code-quality:
    name: Code Quality
    needs: commit-lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2

      - name: Run Biome
        run: biome ci

  build-and-test:
    needs: code-quality
    strategy:
      fail-fast: false
      matrix:
        node:
          - 22
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    name: "${{matrix.platform}} w/ Node.js ${{matrix.node}}.x"
    runs-on: ${{matrix.platform}}

    steps:
      - uses: actions/checkout@v4

      - name: "Use Node.js ${{matrix.node}}.x"
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}.x

      - run: npm install
      - run: npm run build
      - run: npm test
