name: Lint PR

on: [pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
    commit-lint:
        name: Commit Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - uses: wagoid/commitlint-github-action@v6
