name: Publish releases

on:
  push:
    branches: [main]

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created:  ${{ steps.release.outputs.release_created }}
      release_tag:  ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: simple
          package-name: amaro

  npm-publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Publish to the npm registry
        run: |
            npm install
            npm publish
        env:
            NPM_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - run: npm pack --out amaro.tgz
      - name: Add Amaro package archive to GitHub release
        run: gh release upload ${{ needs.release-please.outputs.release_tag }} amaro.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
